:::NVLOGv0.1.0 ncf 1604476219.624366283 (ncf.py:171) cpu_info: {"num": 128, "name": "AMD EPYC 7742 64-Core Processor"}
:::NVLOGv0.1.0 ncf 1604476219.632952213 (ncf.py:171) cpu_info: {"num": 128, "name": "AMD EPYC 7742 64-Core Processor"}
:::NVLOGv0.1.0 ncf 1604476219.635838747 (ncf.py:171) mem_info: {"ram": "1.0T"}
:::NVLOGv0.1.0 ncf 1604476219.642112494 (ncf.py:171) mem_info: {"ram": "1.0T"}
:::NVLOGv0.1.0 ncf 1604476219.642796993 (ncf.py:171) cpu_info: {"num": 128, "name": "AMD EPYC 7742 64-Core Processor"}
:::NVLOGv0.1.0 ncf 1604476219.644019604 (ncf.py:171) cpu_info: {"num": 128, "name": "AMD EPYC 7742 64-Core Processor"}
:::NVLOGv0.1.0 ncf 1604476219.652829170 (ncf.py:171) mem_info: {"ram": "1.0T"}
:::NVLOGv0.1.0 ncf 1604476219.653127193 (ncf.py:171) mem_info: {"ram": "1.0T"}
:::NVLOGv0.1.0 ncf 1604476234.281368732 (ncf.py:171) gpu_info: {"driver_version": "455.32.00", "num": 8, "name": ["A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB"], "mem": ["40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB"]}
:::NVLOGv0.1.0 ncf 1604476234.281817198 (ncf.py:171) gpu_info: {"driver_version": "455.32.00", "num": 8, "name": ["A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB"], "mem": ["40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB"]}
:::NVLOGv0.1.0 ncf 1604476234.283457518 (ncf.py:171) gpu_info: {"driver_version": "455.32.00", "num": 8, "name": ["A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB"], "mem": ["40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB"]}
:::NVLOGv0.1.0 ncf 1604476234.287497282 (ncf.py:171) gpu_info: {"driver_version": "455.32.00", "num": 8, "name": ["A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB", "A100-SXM4-40GB"], "mem": ["40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB", "40536 MiB"]}
:::NVLOGv0.1.0 ncf 1604476236.944608688 (ncf.py:174) args: {"data": "/data/ncf/cache/ml-20m", "epochs": 2, "batch_size": 32000000, "valid_batch_size": 1048576, "factors": 64, "layers": [256, 256, 128, 64], "negative_samples": 4, "learning_rate": 0.0045, "topk": 10, "seed": 1, "threshold": 1.0, "beta1": 0.25, "beta2": 0.5, "eps": 1e-08, "dropout": 0.5, "checkpoint_dir": "/data/checkpoints/", "load_checkpoint_path": null, "mode": "train", "grads_accumulated": 1, "opt_level": "O2", "local_rank": 0, "distributed": true, "world_size": 4}
Saving results to /data/checkpoints/
:::NVLOGv0.1.0 ncf 1604476236.945364475 (ncf.py:184) preproc_hp_sample_eval_replacement: true
:::NVLOGv0.1.0 ncf 1604476236.945935011 (ncf.py:185) input_hp_sample_train_replacement: true
:::NVLOGv0.1.0 ncf 1604476236.946494102 (ncf.py:186) input_step_eval_neg_gen
:::NVLOGv0.1.0 ncf 1604476240.540659189 (ncf.py:194) run_start
Traceback (most recent call last):
  File "ncf.py", line 366, in <module>
    main()
  File "ncf.py", line 198, in main
    test_negs = torch.load(args.data+'/test_negatives.pt', map_location=torch.device('cuda:{}'.format(args.local_rank)))
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/ncf/cache/ml-20m/test_negatives.pt'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'ncf.py', '--local_rank=3', '--data', '/data/ncf/cache/ml-20m', '--epochs', '2', '--batch_size', '32000000', '--opt_level', 'O2']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
DONE!
