Container nvidia build =  85286408
out dir is .
torchrun --nproc_per_node=4 run_squad.py --init_checkpoint=/data/bert_large/bert_large_uncased.pt --do_train --train_file=/data/squad/v1.1/train-v1.1.json --train_batch_size=64  --do_lower_case  --bert_model=bert-large-uncased  --learning_rate=0.0  --warmup_proportion=0.1 --seed=1  --num_train_epochs=2.0  --max_seq_length=384  --doc_stride=128  --output_dir=.  --vocab_file=/data/bert_large/bert-large-uncased-vocab.txt  --config_file=/data/bert_large/bert_config.json  --max_steps=100   |& tee ./logfile.txt
[2024-09-29 07:45:05,370] torch.distributed.run: [WARNING] 
[2024-09-29 07:45:05,370] torch.distributed.run: [WARNING] *****************************************
[2024-09-29 07:45:05,370] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-09-29 07:45:05,370] torch.distributed.run: [WARNING] *****************************************
device: cuda:0 n_gpu: 1, distributed training: True, 16-bits training: False
DLL 2024-09-29 07:45:07.893466 - PARAMETER Config : ["Namespace(bert_model='bert-large-uncased', output_dir='.', init_checkpoint='/data/bert_large/bert_large_uncased.pt', train_file='/data/squad/v1.1/train-v1.1.json', predict_file=None, max_seq_length=384, doc_stride=128, max_query_length=64, do_train=True, do_predict=False, train_batch_size=64, predict_batch_size=8, learning_rate=0.0, num_train_epochs=2.0, max_steps=100.0, warmup_proportion=0.1, n_best_size=20, max_answer_length=30, verbose_logging=False, no_cuda=False, seed=1, gradient_accumulation_steps=1, do_lower_case=True, local_rank=0, fp16=False, amp=False, loss_scale=0, version_2_with_negative=False, null_score_diff_threshold=0.0, vocab_file='/data/bert_large/bert-large-uncased-vocab.txt', config_file='/data/bert_large/bert_config.json', log_freq=50, json_summary='results/dllogger.json', eval_script='evaluate.py', do_eval=False, use_env=False, skip_checkpoint=False, disable_progress_bar=False, skip_cache=False, cache_dir=None)"] 
DLL 2024-09-29 07:45:07.893656 - PARAMETER SEED : 1 
WARNING: Output directory . already exists and is not empty. ['utils.py', 'file_utils.py', 'scripts', 'triton', 'optimization.py', 'tokenization.py', 'lamb_amp_opt', 'run_swag.py', 'logfile.txt', 'processors', 'Dockerfile', 'checkpoints', '__pycache__', 'requirements.txt', 'create_pretraining_data.py', 'modeling.py', 'images', '.gitmodules', 'tokenization_utils.py', 'schedulers.py', 'distillation', 'run_glue.py', 'run_squad.py', 'data', 'results', 'config.json', 'LICENSE', '.gitignore', 'bind_pyt.py', 'vocab', 'pytorch_model.bin', 'extract_features.py', 'inference.py', 'configurations.yml', 'bert_configs', 'run.sub', 'run_pretraining.py', 'NOTICE', '.dockerignore', 'README.md', 'bind.sh']
device: cuda:1 n_gpu: 1, distributed training: True, 16-bits training: False
device: cuda:2 n_gpu: 1, distributed training: True, 16-bits training: False
device: cuda:3 n_gpu: 1, distributed training: True, 16-bits training: False
WARNING: Output directory . already exists and is not empty. ['utils.py', 'file_utils.py', 'scripts', 'triton', 'optimization.py', 'tokenization.py', 'lamb_amp_opt', 'run_swag.py', 'logfile.txt', 'processors', 'Dockerfile', 'checkpoints', '__pycache__', 'requirements.txt', 'create_pretraining_data.py', 'modeling.py', 'images', '.gitmodules', 'tokenization_utils.py', 'schedulers.py', 'distillation', 'run_glue.py', 'run_squad.py', 'data', 'results', 'config.json', 'LICENSE', '.gitignore', 'bind_pyt.py', 'vocab', 'pytorch_model.bin', 'extract_features.py', 'inference.py', 'configurations.yml', 'bert_configs', 'run.sub', 'run_pretraining.py', 'NOTICE', '.dockerignore', 'README.md', 'bind.sh']
WARNING: Output directory . already exists and is not empty.WARNING: Output directory . already exists and is not empty.  ['utils.py', 'file_utils.py', 'scripts', 'triton', 'optimization.py', 'tokenization.py', 'lamb_amp_opt', 'run_swag.py', 'logfile.txt', 'processors', 'Dockerfile', 'checkpoints', '__pycache__', 'requirements.txt', 'create_pretraining_data.py', 'modeling.py', 'images', '.gitmodules', 'tokenization_utils.py', 'schedulers.py', 'distillation', 'run_glue.py', 'run_squad.py', 'data', 'results', 'config.json', 'LICENSE', '.gitignore', 'bind_pyt.py', 'vocab', 'pytorch_model.bin', 'extract_features.py', 'inference.py', 'configurations.yml', 'bert_configs', 'run.sub', 'run_pretraining.py', 'NOTICE', '.dockerignore', 'README.md', 'bind.sh']
['utils.py', 'file_utils.py', 'scripts', 'triton', 'optimization.py', 'tokenization.py', 'lamb_amp_opt', 'run_swag.py', 'logfile.txt', 'processors', 'Dockerfile', 'checkpoints', '__pycache__', 'requirements.txt', 'create_pretraining_data.py', 'modeling.py', 'images', '.gitmodules', 'tokenization_utils.py', 'schedulers.py', 'distillation', 'run_glue.py', 'run_squad.py', 'data', 'results', 'config.json', 'LICENSE', '.gitignore', 'bind_pyt.py', 'vocab', 'pytorch_model.bin', 'extract_features.py', 'inference.py', 'configurations.yml', 'bert_configs', 'run.sub', 'run_pretraining.py', 'NOTICE', '.dockerignore', 'README.md', 'bind.sh']
DLL 2024-09-29 07:45:14.703049 - PARAMETER loading_checkpoint : True 
DLL 2024-09-29 07:45:14.703198 - PARAMETER loaded_checkpoint : True 
DLL 2024-09-29 07:45:15.115807 - PARAMETER model_weights_num : 335150082 
/usr/local/lib/python3.10/dist-packages/apex/__init__.py:68: DeprecatedFeatureWarning: apex.parallel.DistributedDataParallel is deprecated and will be removed by the end of February 2023.
  warnings.warn(msg, DeprecatedFeatureWarning)
/usr/local/lib/python3.10/dist-packages/apex/parallel/distributed.py:253: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:79.)
  self._overflow_buf = torch.cuda.IntTensor([0])
/usr/local/lib/python3.10/dist-packages/apex/parallel/distributed.py:253: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:79.)
  self._overflow_buf = torch.cuda.IntTensor([0])
/usr/local/lib/python3.10/dist-packages/apex/parallel/distributed.py:253: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:79.)
  self._overflow_buf = torch.cuda.IntTensor([0])
/usr/local/lib/python3.10/dist-packages/apex/parallel/distributed.py:253: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:79.)
  self._overflow_buf = torch.cuda.IntTensor([0])
[rank3]: Traceback (most recent call last):
[rank3]:   File "/workspace/benchmark/LanguageModeling/BERT/run_squad.py", line 1199, in <module>
[rank3]:     main()
[rank3]:   File "/workspace/benchmark/LanguageModeling/BERT/run_squad.py", line 983, in main
[rank3]:     model = DDP(model)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/apex/parallel/distributed.py", line 257, in __init__
[rank3]:     flat_dist_call([param.data for param in self.module.parameters()], dist.broadcast, (0,) )
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/apex/parallel/distributed.py", line 77, in flat_dist_call
[rank3]:     apply_flat_dist_call(bucket, call, extra_args)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/apex/parallel/distributed.py", line 43, in apply_flat_dist_call
[rank3]:     call(coalesced, *extra_args)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank3]:     return func(*args, **kwargs)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2045, in broadcast
[rank3]:     work = default_pg.broadcast([tensor], opts)
[rank3]: torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2006, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.20.5
[rank3]: ncclUnhandledCudaError: Call to CUDA function failed.
[rank3]: Last error:
[rank3]: Cuda failure 801 'operation not supported'
[2024-09-29 07:45:20,391] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 6759 closing signal SIGTERM
[2024-09-29 07:45:20,391] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 6760 closing signal SIGTERM
[2024-09-29 07:45:20,391] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 6761 closing signal SIGTERM
[2024-09-29 07:45:20,856] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 3 (pid: 6762) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 834, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 825, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 137, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 271, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_squad.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-29_07:45:20
  host      : 8f5a528b3a5a
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 6762)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

real	0m16.610s
user	0m37.199s
sys	0m23.115s
DONE!
